log_prefix = ' *MAITENANCE* '
user_not_exist = 'Can not find %s, please check the user name.'
failed_to_add_object = 'Failed to add %s, please check whether the it is already exist. If still has problem, please contact support.'
failed_to_delete_object = 'Failed to delete %s, please contact system supports.'
failed_to_get_object = 'Failed to get %s, please contact system supports.'
failed_to_update_object = 'Failed to update %s, please contact system supports.'
failed_to_add_leave_type = 'Failed to add Leave Type %s, please check whether the it is already exist. If still has problem, please contact support.'